### PR TITLE
Input element for form integration

### PR DESCRIPTION
**Pull request by lootic**
Added a config element for 'input' to make it easier to integrate with forms in a site. It is supposed to be configured the same way other such config elements use like 'editor'.

### CODE REVIEW

**Comment by lootic** [comment]
My first pull request, please have mercy. If it sucks please tell me why so I can learn.

:)

**Comment by ypnos-web** [comment]
Great PR!
I would suggest the option to fill the input with markdown instead of html.

**Comment by lootic** [comment]
Added the suggested option. It's configured via the flag 'saveAsMarkdown' when you initialize your pen.

**Comment by ypnos-web** [comment]
Looks great! I hope it gets merged soon.

**Pull request merged**
